"""
EPUB export helpers for generated chapter files.
"""

from __future__ import annotations

import html
import json
import os
import re
import textwrap
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from xml.sax.saxutils import escape as xml_escape


@dataclass(frozen=True)
class EbookChapter:
    number: int
    title: str
    filename: str
    content: str


def export_epub(project_dir: str | os.PathLike[str], output_path: str | os.PathLike[str] | None = None) -> str:
    """Build a minimal EPUB from a generated book project."""
    project_path = Path(project_dir)
    project_data = _load_project_data(project_path)
    chapters = _load_chapters(project_path, project_data)
    if not chapters:
        raise ValueError(f"No chapter files found in '{project_path}'.")

    title = _resolve_book_title(project_data, project_path, chapters)
    author = "AI Book Creator"
    output_file = Path(output_path) if output_path else project_path / f"{_slugify(title)}.epub"
    output_file.parent.mkdir(parents=True, exist_ok=True)

    book_id = _slugify(title) or "ai-book-creator-book"
    description = project_data.get("init", {}).get("book_idea", "Generated by AI Book Creator.")
    language = "en"
    created_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    with zipfile.ZipFile(output_file, "w") as epub:
        _write_mimetype(epub)
        _write_container(epub)
        _write_nav(epub, title, chapters)
        _write_chapters(epub, chapters)
        _write_css(epub)
        _write_content_opf(
            epub,
            book_id=book_id,
            title=title,
            author=author,
            description=description,
            language=language,
            created_at=created_at,
            chapters=chapters,
        )

    return str(output_file)


def _load_project_data(project_path: Path) -> dict[str, Any]:
    project_file = project_path / "project_data.json"
    if not project_file.exists():
        return {}
    with project_file.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, dict) else {}


def _load_chapters(project_path: Path, project_data: dict[str, Any]) -> list[EbookChapter]:
    written = project_data.get("written", {})
    chapter_map = written.get("chapters", {}) if isinstance(written, dict) else {}
    chapters: list[EbookChapter] = []

    for chapter_key, info in chapter_map.items():
        if not isinstance(info, dict):
            continue
        filename = info.get("filename")
        if not filename:
            continue
        chapter_path = project_path / filename
        if not chapter_path.exists():
            continue

        content = chapter_path.read_text(encoding="utf-8")
        number = int(info.get("chapter_number") or _chapter_number_from_key(chapter_key))
        title = str(info.get("title") or _extract_chapter_title(content) or f"Chapter {number}")
        chapters.append(EbookChapter(number=number, title=title, filename=str(chapter_path), content=content))

    chapters.sort(key=lambda chapter: chapter.number)
    return chapters


def _resolve_book_title(project_data: dict[str, Any], project_path: Path, chapters: list[EbookChapter]) -> str:
    init_data = project_data.get("init", {}) if isinstance(project_data.get("init", {}), dict) else {}
    layout_content = str(init_data.get("layout_content", ""))
    titles = re.findall(r"\*\*([^*]{3,120})\*\*", layout_content)
    if titles:
        return titles[0].strip()

    title_line = re.search(r"^\s*#\s*(.+?)\s*$", chapters[0].content, re.MULTILINE)
    if title_line:
        return title_line.group(1).lstrip("# ").strip()[:120]

    return project_path.name.replace("_", " ").replace("-", " ").strip().title() or "Generated Book"


def _extract_chapter_title(content: str) -> str:
    first_heading = re.search(r"^\s*#\s*(.+?)\s*$", content, re.MULTILINE)
    if first_heading:
        return first_heading.group(1).strip()
    return ""


def _chapter_number_from_key(chapter_key: str) -> int:
    match = re.search(r"(\d+)$", chapter_key)
    return int(match.group(1)) if match else 0


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", text.lower()).strip("-")
    return slug or "generated-book"


def _write_mimetype(epub: zipfile.ZipFile) -> None:
    epub.writestr("mimetype", "application/epub+zip", compress_type=zipfile.ZIP_STORED)


def _write_container(epub: zipfile.ZipFile) -> None:
    container_xml = """<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
"""
    epub.writestr("META-INF/container.xml", container_xml)


def _write_nav(epub: zipfile.ZipFile, title: str, chapters: Iterable[EbookChapter]) -> None:
    nav_items = []
    for chapter in chapters:
        nav_items.append(
            f'<li><a href="text/chapter-{chapter.number:02d}.xhtml">{html.escape(chapter.title)}</a></li>'
        )

    nav_xhtml = """<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{title}</title>
    <link rel="stylesheet" type="text/css" href="styles/style.css" />
  </head>
  <body>
    <nav epub:type="toc" id="toc">
      <h1>{title}</h1>
      <ol>
        {items}
      </ol>
    </nav>
  </body>
</html>
""".format(title=html.escape(title), items="\n        ".join(nav_items))
    epub.writestr("OEBPS/nav.xhtml", nav_xhtml)


def _write_css(epub: zipfile.ZipFile) -> None:
    css = textwrap.dedent(
        """
        body {
            font-family: serif;
            line-height: 1.55;
            margin: 0;
            padding: 0 1.1em 2em;
            color: #111;
            background: #fff;
        }
        h1 {
            font-size: 1.8em;
            margin: 1.2em 0 0.7em;
            line-height: 1.2;
        }
        h2 {
            font-size: 1.2em;
            margin: 1.1em 0 0.6em;
        }
        p {
            margin: 0 0 0.85em;
            text-align: left;
        }
        .chapter {
            max-width: 42em;
            margin: 0 auto;
        }
        .scene-break {
            text-align: center;
            letter-spacing: 0.2em;
            margin: 1em 0;
        }
        """
    ).strip()
    epub.writestr("OEBPS/styles/style.css", css)


def _write_chapters(epub: zipfile.ZipFile, chapters: Iterable[EbookChapter]) -> None:
    for chapter in chapters:
        xhtml = _render_chapter_xhtml(chapter)
        epub.writestr(f"OEBPS/text/chapter-{chapter.number:02d}.xhtml", xhtml)


def _render_chapter_xhtml(chapter: EbookChapter) -> str:
    title, body_blocks = _split_chapter_content(chapter.content)
    heading = html.escape(title or chapter.title)
    paragraphs = []
    for block in body_blocks:
        block = block.strip()
        if not block:
            continue
        if block.startswith("###"):
            paragraphs.append(f"<h2>{html.escape(block.lstrip('#').strip())}</h2>")
            continue
        if block.startswith("##"):
            paragraphs.append(f"<h2>{html.escape(block.lstrip('#').strip())}</h2>")
            continue
        if block.startswith("#"):
            paragraphs.append(f"<h1>{html.escape(block.lstrip('#').strip())}</h1>")
            continue
        paragraphs.append(f"<p>{_inline_format(block)}</p>")

    body_html = "\n      ".join(paragraphs) if paragraphs else "<p></p>"
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{heading}</title>
    <link rel="stylesheet" type="text/css" href="../styles/style.css" />
  </head>
  <body>
    <article class="chapter">
      <h1>{heading}</h1>
      {body_html}
    </article>
  </body>
</html>
"""


def _split_chapter_content(content: str) -> tuple[str, list[str]]:
    lines = content.splitlines()
    title = ""
    remaining: list[str] = []
    title_consumed = False

    for line in lines:
        stripped = line.strip()
        if not stripped:
            if title_consumed:
                remaining.append("")
            continue
        if not title_consumed and stripped.startswith("#"):
            title = stripped.lstrip("#").strip()
            title_consumed = True
            continue
        title_consumed = True
        remaining.append(line)

    blocks: list[str] = []
    current: list[str] = []
    for line in remaining:
        if not line.strip():
            if current:
                blocks.append("\n".join(current).strip())
                current = []
            continue
        current.append(line)
    if current:
        blocks.append("\n".join(current).strip())

    return title, blocks


def _inline_format(text: str) -> str:
    escaped = html.escape(text)
    escaped = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"\*(.+?)\*", r"<em>\1</em>", escaped)
    return escaped


def _write_content_opf(
    epub: zipfile.ZipFile,
    *,
    book_id: str,
    title: str,
    author: str,
    description: str,
    language: str,
    created_at: str,
    chapters: Iterable[EbookChapter],
) -> None:
    manifest_items = [
        '<item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>',
        '<item id="css" href="styles/style.css" media-type="text/css"/>',
    ]
    spine_items = []
    for chapter in chapters:
        file_name = f"text/chapter-{chapter.number:02d}.xhtml"
        item_id = f"chapter-{chapter.number:02d}"
        manifest_items.append(
            f'<item id="{item_id}" href="{file_name}" media-type="application/xhtml+xml"/>'
        )
        spine_items.append(f'<itemref idref="{item_id}"/>')

    opf = f"""<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="book-id" xml:lang="{xml_escape(language)}">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="book-id">{xml_escape(book_id)}</dc:identifier>
    <dc:title>{xml_escape(title)}</dc:title>
    <dc:language>{xml_escape(language)}</dc:language>
    <dc:creator>{xml_escape(author)}</dc:creator>
    <dc:description>{xml_escape(description)}</dc:description>
    <meta property="dcterms:modified">{xml_escape(created_at)}</meta>
  </metadata>
  <manifest>
    {' '.join(manifest_items)}
  </manifest>
  <spine>
    {' '.join(spine_items)}
  </spine>
</package>
"""
    epub.writestr("OEBPS/content.opf", opf)
