"""
EPUB export helpers for generated chapter files.
"""

from __future__ import annotations

import html
import json
import os
import re
import textwrap
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from xml.sax.saxutils import escape as xml_escape


@dataclass(frozen=True)
class EbookChapter:
    number: int
    title: str
    filename: str
    content: str


@dataclass(frozen=True)
class EbookImage:
    source_path: Path
    epub_path: str
    media_type: str


def export_epub(project_dir: str | os.PathLike[str], output_path: str | os.PathLike[str] | None = None) -> str:
    """Build a minimal EPUB from a generated book project."""
    project_path = Path(project_dir)
    project_data = _load_project_data(project_path)
    provider_info = _load_provider_info(project_path)
    chapters = _load_chapters(project_path, project_data)
    if not chapters:
        raise ValueError(f"No chapter files found in '{project_path}'.")
    images = _collect_image_assets(chapters, project_path)

    title = _resolve_book_title(project_data, project_path, chapters)
    author = "AI Book Creator"
    output_file = Path(output_path) if output_path else project_path / "ebook" / f"{_slugify(title)}.epub"
    output_file.parent.mkdir(parents=True, exist_ok=True)

    book_id = _slugify(title) or "ai-book-creator-book"
    description = project_data.get("init", {}).get("book_idea", "Generated by AI Book Creator.")
    language = "en"
    created_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    with zipfile.ZipFile(output_file, "w") as epub:
        _write_mimetype(epub)
        _write_container(epub)
        _write_nav(epub, title, chapters)
        _write_frontmatter(epub, title, provider_info)
        _write_chapters(epub, chapters, project_path, images)
        _write_images(epub, images)
        _write_css(epub)
        _write_content_opf(
            epub,
            book_id=book_id,
            title=title,
            author=author,
            description=description,
            language=language,
            created_at=created_at,
            chapters=chapters,
            images=images,
        )

    _write_cover_prompt_file(output_file, project_data, title, chapters)
    return str(output_file)


def _load_project_data(project_path: Path) -> dict[str, Any]:
    project_file = project_path / "project_data.json"
    if not project_file.exists():
        return {}
    with project_file.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, dict) else {}


def _load_provider_info(project_path: Path) -> dict[str, Any]:
    state_file = project_path / "provider_state.json"
    if not state_file.exists():
        return {}
    try:
        with state_file.open("r", encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def _load_chapters(project_path: Path, project_data: dict[str, Any]) -> list[EbookChapter]:
    written = project_data.get("written", {})
    chapter_map = written.get("chapters", {}) if isinstance(written, dict) else {}
    chapters: list[EbookChapter] = []

    for chapter_key, info in chapter_map.items():
        if not isinstance(info, dict):
            continue
        filename = info.get("filename")
        if not filename:
            continue
        chapter_path = _resolve_project_file(project_path, str(filename))
        if chapter_path is None:
            continue

        content = chapter_path.read_text(encoding="utf-8")
        number = int(info.get("chapter_number") or _chapter_number_from_key(chapter_key))
        title = str(info.get("title") or _extract_chapter_title(content) or f"Chapter {number}")
        chapters.append(EbookChapter(number=number, title=title, filename=str(chapter_path), content=content))

    chapters.sort(key=lambda chapter: chapter.number)
    return chapters


def _resolve_book_title(project_data: dict[str, Any], project_path: Path, chapters: list[EbookChapter]) -> str:
    init_data = project_data.get("init", {}) if isinstance(project_data.get("init", {}), dict) else {}
    layout_content = str(init_data.get("layout_content", ""))
    titles = re.findall(r"\*\*([^*]{3,120})\*\*", layout_content)
    if titles:
        return titles[0].strip()

    title_line = re.search(r"^\s*#\s*(.+?)\s*$", chapters[0].content, re.MULTILINE)
    if title_line:
        return title_line.group(1).lstrip("# ").strip()[:120]

    return project_path.name.replace("_", " ").replace("-", " ").strip().title() or "Generated Book"


def _write_cover_prompt_file(output_file: Path, project_data: dict[str, Any], title: str, chapters: list[EbookChapter]) -> str:
    prompt_path = output_file.with_name(f"{output_file.stem}_cover_prompt.txt")
    prompt = _build_cover_prompt(project_data, title, chapters)
    prompt_path.write_text(prompt, encoding="utf-8")
    return str(prompt_path)


def _build_cover_prompt(project_data: dict[str, Any], title: str, chapters: list[EbookChapter]) -> str:
    init_data = project_data.get("init", {}) if isinstance(project_data.get("init", {}), dict) else {}
    book_idea = str(init_data.get("book_idea", "")).strip()
    layout_content = str(init_data.get("layout_content", "")).strip()
    series_layout_content = str(init_data.get("series_layout_content", "")).strip()
    written = project_data.get("written", {}) if isinstance(project_data.get("written", {}), dict) else {}
    reviewed = project_data.get("reviewed", {}) if isinstance(project_data.get("reviewed", {}), dict) else {}

    chapter_titles = [chapter.title for chapter in chapters[:5] if chapter.title]
    mood = _extract_cover_mood(layout_content) or "dramatic and cinematic"
    genre = _extract_cover_genre(layout_content) or "literary fiction"
    visual_keywords = _extract_cover_keywords(layout_content, book_idea, reviewed.get("analysis", ""))
    if not visual_keywords and chapter_titles:
        visual_keywords = chapter_titles[:3]

    prompt_lines = [
        f"Book cover prompt for: {title}",
        f"Create a striking, professional book cover in a {mood} style for a {genre} novel.",
        "Square composition, strong focal point, polished lighting, high-detail digital illustration.",
    ]
    if book_idea:
        prompt_lines.append(f"Story premise: {book_idea}")
    if series_layout_content:
        prompt_lines.append(f"Series context: {series_layout_content[:900]}")
    if visual_keywords:
        prompt_lines.append(f"Include these visual elements: {', '.join(visual_keywords[:6])}.")
    if chapter_titles:
        prompt_lines.append(f"Key chapter or scene cues: {', '.join(chapter_titles[:5])}.")
    if written.get("total_word_count"):
        prompt_lines.append(f"Manuscript length: {int(written.get('total_word_count', 0)):,} words.")
    prompt_lines.append("Do not add text overlays, watermarks, or logos.")

    return "\n".join(prompt_lines).strip() + "\n"


def _extract_cover_mood(layout_content: str) -> str:
    mood_patterns = [
        r"mood[:\s-]+([^\n;]{3,80})",
        r"tone[:\s-]+([^\n;]{3,80})",
        r"atmosphere[:\s-]+([^\n;]{3,80})",
    ]
    for pattern in mood_patterns:
        match = re.search(pattern, layout_content, re.IGNORECASE)
        if match:
            return match.group(1).strip().rstrip(".")
    return ""


def _extract_cover_genre(layout_content: str) -> str:
    match = re.search(r"genre[:\s-]+([^\n;]{3,80})", layout_content, re.IGNORECASE)
    if match:
        return match.group(1).strip().rstrip(".")
    return ""


def _extract_cover_keywords(*sources: str) -> list[str]:
    keywords: list[str] = []
    seen: set[str] = set()
    for source in sources:
        for match in re.findall(r"\b[A-Z][a-zA-Z]{3,}\b", source):
            normalized = match.lower()
            if normalized in seen:
                continue
            if normalized in {"chapter", "title", "genre", "setting", "theme"}:
                continue
            seen.add(normalized)
            keywords.append(match)
    return keywords


def _extract_chapter_title(content: str) -> str:
    first_heading = re.search(r"^\s*#\s*(.+?)\s*$", content, re.MULTILINE)
    if first_heading:
        return first_heading.group(1).strip()
    return ""


def _chapter_number_from_key(chapter_key: str) -> int:
    match = re.search(r"(\d+)$", chapter_key)
    return int(match.group(1)) if match else 0


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", text.lower()).strip("-")
    return slug or "generated-book"


def _write_mimetype(epub: zipfile.ZipFile) -> None:
    epub.writestr("mimetype", "application/epub+zip", compress_type=zipfile.ZIP_STORED)


def _write_container(epub: zipfile.ZipFile) -> None:
    container_xml = """<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
"""
    epub.writestr("META-INF/container.xml", container_xml)


def _write_nav(epub: zipfile.ZipFile, title: str, chapters: Iterable[EbookChapter]) -> None:
    nav_items = [
        '<li><a href="text/title_page.xhtml">Title Page</a></li>',
        '<li><a href="text/disclaimer.xhtml">Disclaimer</a></li>'
    ]
    for chapter in chapters:
        nav_items.append(
            f'<li><a href="text/chapter-{chapter.number:02d}.xhtml">{html.escape(chapter.title)}</a></li>'
        )

    nav_xhtml = """<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{title}</title>
    <link rel="stylesheet" type="text/css" href="styles/style.css" />
  </head>
  <body>
    <nav epub:type="toc" id="toc">
      <h1>{title}</h1>
      <ol>
        {items}
      </ol>
    </nav>
  </body>
</html>
""".format(title=html.escape(title), items="\n        ".join(nav_items))
    epub.writestr("OEBPS/nav.xhtml", nav_xhtml)


def _write_frontmatter(epub: zipfile.ZipFile, title: str, provider_info: dict[str, str]) -> None:
    # 1. Title Page
    title_xhtml = f"""<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Title Page</title>
    <link rel="stylesheet" type="text/css" href="../styles/style.css" />
  </head>
  <body>
    <div class="title-page">
      <h1>{html.escape(title)}</h1>
      <h3>Generated by AI Book Creator</h3>
    </div>
  </body>
</html>
"""
    epub.writestr("OEBPS/text/title_page.xhtml", title_xhtml)

    # 2. Disclaimer Page
    provider = provider_info.get("provider", "AI")
    model = provider_info.get("openai_model") or provider_info.get("writing_model") or "Language Model"
    
    if provider.lower() == "openai" and "gpt" in model.lower():
        model_text = f"OpenAI ({model})"
    elif provider.lower() == "groq":
        model_text = f"Groq ({model})"
    elif provider.lower() == "google":
        model_text = f"Google Gemini ({model})"
    else:
        model_text = f"{provider.title()} ({model})"

    disclaimer_xhtml = f"""<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Disclaimer</title>
    <link rel="stylesheet" type="text/css" href="../styles/style.css" />
  </head>
  <body>
    <article class="chapter">
      <h1>Disclaimer</h1>
      <p>This book was entirely generated by an Artificial Intelligence language model. All characters, locations, events, and scenarios described within are either products of the AI's generation or are used fictitiously. Any resemblance to actual persons, living or dead, or actual events is purely coincidental.</p>
      <p>The creators, maintainers, and users of this AI generation system claim no copyright over the generated text, but advise that AI-generated content may be subject to varying legal interpretations regarding copyright, intellectual property, and ownership in different jurisdictions.</p>
      <p><strong>Model Used:</strong> {html.escape(model_text)}</p>
    </article>
  </body>
</html>
"""
    epub.writestr("OEBPS/text/disclaimer.xhtml", disclaimer_xhtml)


def _write_css(epub: zipfile.ZipFile) -> None:
    css = textwrap.dedent(
        """
        body {
            font-family: serif;
            line-height: 1.55;
            margin: 0;
            padding: 0 1.1em 2em;
            color: #111;
            background: #fff;
        }
        h1 {
            font-size: 1.8em;
            margin: 1.2em 0 0.7em;
            line-height: 1.2;
        }
        h2 {
            font-size: 1.2em;
            margin: 1.1em 0 0.6em;
        }
        p {
            margin: 0 0 0.85em;
            text-align: left;
        }
        blockquote {
            margin: 1em 0;
            padding: 0.2em 1em;
            border-left: 0.2em solid #999;
            color: #444;
        }
        ul, ol {
            margin: 0 0 0.85em 1.5em;
            padding: 0;
        }
        li {
            margin: 0 0 0.35em;
        }
        figure {
            margin: 1.2em auto;
            text-align: center;
        }
        figure img {
            max-width: 100%;
            height: auto;
        }
        figcaption {
            font-size: 0.9em;
            color: #555;
            margin-top: 0.4em;
        }
        .chapter {
            max-width: 42em;
            margin: 0 auto;
        }
        .scene-break {
            text-align: center;
            letter-spacing: 0.2em;
            margin: 1em 0;
        }
        .title-page {
            text-align: center;
            margin-top: 30vh;
        }
        .title-page h1 {
            font-size: 2.5em;
            margin-bottom: 0.2em;
            border: none;
        }
        .title-page h3 {
            font-size: 1.2em;
            font-weight: normal;
            color: #555;
        }
        """
    ).strip()
    epub.writestr("OEBPS/styles/style.css", css)


def _write_chapters(epub: zipfile.ZipFile, chapters: Iterable[EbookChapter], project_path: Path, images: list[EbookImage]) -> None:
    image_lookup = {image.source_path.resolve(): image for image in images}
    for chapter in chapters:
        xhtml = _render_chapter_xhtml(chapter, project_path, image_lookup)
        epub.writestr(f"OEBPS/text/chapter-{chapter.number:02d}.xhtml", xhtml)


def _write_images(epub: zipfile.ZipFile, images: list[EbookImage]) -> None:
    for image in images:
        epub.write(image.source_path, f"OEBPS/{image.epub_path}")


def _render_chapter_xhtml(chapter: EbookChapter, project_path: Path, image_lookup: dict[Path, EbookImage]) -> str:
    title, body_blocks = _split_chapter_content(chapter.content)
    heading = html.escape(title or chapter.title)
    paragraphs = []
    for block in body_blocks:
        rendered = _render_markdown_block(block, Path(chapter.filename).parent if chapter.filename else project_path, image_lookup)
        if not rendered:
            continue
        paragraphs.extend(rendered)

    body_html = "\n      ".join(paragraphs) if paragraphs else "<p></p>"
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{heading}</title>
    <link rel="stylesheet" type="text/css" href="../styles/style.css" />
  </head>
  <body>
    <article class="chapter">
      <h1>{heading}</h1>
      {body_html}
    </article>
  </body>
</html>
"""


def _render_markdown_block(block: str, base_dir: Path, image_lookup: dict[Path, EbookImage]) -> list[str]:
    lines = [line.rstrip() for line in block.splitlines()]
    output: list[str] = []
    paragraph_buffer: list[str] = []
    list_kind: str | None = None
    list_items: list[str] = []
    quote_lines: list[str] = []

    def flush_paragraph() -> None:
        nonlocal paragraph_buffer
        if paragraph_buffer:
            output.append(f"<p>{_inline_format(' '.join(paragraph_buffer).strip(), base_dir, image_lookup)}</p>")
            paragraph_buffer = []

    def flush_list() -> None:
        nonlocal list_kind, list_items
        if list_items:
            tag = "ol" if list_kind == "ol" else "ul"
            output.append(f"<{tag}>" + "".join(f"<li>{item}</li>" for item in list_items) + f"</{tag}>")
            list_items = []
            list_kind = None

    def flush_quote() -> None:
        nonlocal quote_lines
        if quote_lines:
            quote_text = " ".join(quote_lines).strip()
            output.append(f"<blockquote><p>{_inline_format(quote_text, base_dir, image_lookup)}</p></blockquote>")
            quote_lines = []

    for raw_line in lines:
        line = raw_line.strip()
        if not line:
            flush_paragraph()
            flush_list()
            flush_quote()
            continue

        if re.fullmatch(r"(\*\s*){3,}|(-\s*){3,}|_{3,}", line):
            flush_paragraph()
            flush_list()
            flush_quote()
            output.append('<div class="scene-break">***</div>')
            continue

        heading_match = re.match(r"^(#{1,6})\s+(.+)$", line)
        if heading_match:
            flush_paragraph()
            flush_list()
            flush_quote()
            level = min(len(heading_match.group(1)), 6)
            text = _inline_format(heading_match.group(2), base_dir, image_lookup)
            output.append(f"<h{level}>{text}</h{level}>")
            continue

        quote_match = re.match(r"^>\s?(.*)$", line)
        if quote_match:
            flush_paragraph()
            flush_list()
            quote_lines.append(quote_match.group(1).strip())
            continue

        unordered_match = re.match(r"^[-*+]\s+(.+)$", line)
        ordered_match = re.match(r"^\d+\.\s+(.+)$", line)
        if unordered_match or ordered_match:
            flush_paragraph()
            flush_quote()
            kind = "ol" if ordered_match else "ul"
            if list_kind and list_kind != kind:
                flush_list()
            list_kind = kind
            item_text = ordered_match.group(1) if ordered_match else unordered_match.group(1)
            list_items.append(_inline_format(item_text, base_dir, image_lookup))
            continue

        flush_quote()
        flush_list()
        paragraph_buffer.append(line)

    flush_paragraph()
    flush_list()
    flush_quote()
    return output


def _split_chapter_content(content: str) -> tuple[str, list[str]]:
    lines = content.splitlines()
    title = ""
    remaining: list[str] = []
    title_consumed = False

    for line in lines:
        stripped = line.strip()
        if not stripped:
            if title_consumed:
                remaining.append("")
            continue
        if not title_consumed and stripped.startswith("#"):
            title = stripped.lstrip("#").strip()
            title_consumed = True
            continue
        title_consumed = True
        remaining.append(line)

    blocks: list[str] = []
    current: list[str] = []
    for line in remaining:
        if not line.strip():
            if current:
                blocks.append("\n".join(current).strip())
                current = []
            continue
        current.append(line)
    if current:
        blocks.append("\n".join(current).strip())

    return title, blocks


def _inline_format(text: str, base_dir: Path, image_lookup: dict[Path, EbookImage]) -> str:
    image_markers: dict[str, str] = {}

    def replace_image(match: re.Match[str]) -> str:
        alt_text = match.group(1).strip()
        target = match.group(2).strip()
        resolved = _resolve_markdown_path(base_dir, target)
        image = image_lookup.get(resolved.resolve()) if resolved else None
        if image is None:
            marker = f"__IMAGE_MISSING_{len(image_markers)}__"
            image_markers[marker] = f'<span class="image-missing">[Image: {html.escape(alt_text)}]</span>'
            return marker
        marker = f"__IMAGE_{len(image_markers)}__"
        image_html = (
            f'<figure class="image-block">'
            f'<img src="../{html.escape(image.epub_path)}" alt="{html.escape(alt_text)}" />'
            f'{f"<figcaption>{html.escape(alt_text)}</figcaption>" if alt_text else ""}'
            f"</figure>"
        )
        image_markers[marker] = image_html
        return marker

    text = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", replace_image, text)
    escaped = html.escape(text)
    escaped = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"(?<!\*)\*(?!\s)(.+?)(?<!\s)\*(?!\*)", r"<em>\1</em>", escaped)
    escaped = re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)
    for marker, image_html in image_markers.items():
        escaped = escaped.replace(html.escape(marker), image_html)
    return escaped


def _resolve_markdown_path(base_dir: Path, target: str) -> Path | None:
    target_path = Path(target)
    if target_path.is_absolute():
        return target_path if target_path.exists() else None
    resolved = (base_dir / target_path).resolve()
    return resolved if resolved.exists() else None


def _resolve_project_file(project_path: Path, stored_path: str) -> Path | None:
    """Resolve a chapter or asset path stored in project data.

    Historical projects may store chapter filenames as:
    - absolute paths
    - paths relative to the repository root
    - paths relative to the project directory
    """
    candidates = []
    if not Path(stored_path).is_absolute():
        candidates.append(project_path / stored_path)
        candidates.append(project_path.parent / stored_path)

        project_name_prefix = f"{project_path.name}{os.sep}"
        if stored_path.startswith(project_name_prefix):
            candidates.append(Path(stored_path[len(project_name_prefix):]))
    candidates.append(Path(stored_path))

    seen: set[Path] = set()
    for candidate in candidates:
        try:
            normalized = candidate.resolve()
        except Exception:
            continue
        if normalized in seen:
            continue
        seen.add(normalized)
        if normalized.exists():
            return normalized
    return None


def _collect_image_assets(chapters: Iterable[EbookChapter], project_path: Path) -> list[EbookImage]:
    seen: dict[Path, EbookImage] = {}
    counters: dict[str, int] = {}
    for chapter in chapters:
        chapter_dir = Path(chapter.filename).parent if chapter.filename else project_path
        for match in re.finditer(r"!\[[^\]]*\]\(([^)]+)\)", chapter.content):
            resolved = _resolve_markdown_path(chapter_dir, match.group(1).strip())
            if resolved is None:
                continue
            resolved = resolved.resolve()
            if resolved in seen:
                continue
            ext = resolved.suffix.lower()
            media_type = {
                ".jpg": "image/jpeg",
                ".jpeg": "image/jpeg",
                ".png": "image/png",
                ".gif": "image/gif",
                ".svg": "image/svg+xml",
                ".webp": "image/webp",
            }.get(ext, "application/octet-stream")
            counters.setdefault(ext or ".bin", 0)
            counters[ext or ".bin"] += 1
            epub_name = f"images/image-{counters[ext or '.bin']:03d}{ext or '.bin'}"
            seen[resolved] = EbookImage(source_path=resolved, epub_path=epub_name, media_type=media_type)
    return list(seen.values())


def _write_content_opf(
    epub: zipfile.ZipFile,
    *,
    book_id: str,
    title: str,
    author: str,
    description: str,
    language: str,
    created_at: str,
    chapters: Iterable[EbookChapter],
    images: Iterable[EbookImage],
) -> None:
    manifest_items = [
        '<item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>',
        '<item id="css" href="styles/style.css" media-type="text/css"/>',
        '<item id="title-page" href="text/title_page.xhtml" media-type="application/xhtml+xml"/>',
        '<item id="disclaimer" href="text/disclaimer.xhtml" media-type="application/xhtml+xml"/>',
    ]
    spine_items = [
        '<itemref idref="title-page"/>',
        '<itemref idref="disclaimer"/>',
    ]
    for chapter in chapters:
        file_name = f"text/chapter-{chapter.number:02d}.xhtml"
        item_id = f"chapter-{chapter.number:02d}"
        manifest_items.append(
            f'<item id="{item_id}" href="{file_name}" media-type="application/xhtml+xml"/>'
        )
        spine_items.append(f'<itemref idref="{item_id}"/>')
    for index, image in enumerate(images, start=1):
        item_id = f"image-{index:03d}"
        manifest_items.append(
            f'<item id="{item_id}" href="{image.epub_path}" media-type="{image.media_type}"/>'
        )

    opf = f"""<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="book-id" xml:lang="{xml_escape(language)}">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="book-id">{xml_escape(book_id)}</dc:identifier>
    <dc:title>{xml_escape(title)}</dc:title>
    <dc:language>{xml_escape(language)}</dc:language>
    <dc:creator>{xml_escape(author)}</dc:creator>
    <dc:description>{xml_escape(description)}</dc:description>
    <meta property="dcterms:modified">{xml_escape(created_at)}</meta>
  </metadata>
  <manifest>
    {' '.join(manifest_items)}
  </manifest>
  <spine>
    {' '.join(spine_items)}
  </spine>
</package>
"""
    epub.writestr("OEBPS/content.opf", opf)